export const ATTEMPT_LOGIN = 'ATTEMPT_LOGIN'

export const LOGIN_STATUS_STATES = {
    NOT_LOGGED_IN: 'NOT_LOGGED_IN',
    ATTEMPTING_LOGIN: 'ATTEMPTING_LOGIN',
    LOGGED_IN: 'LOGGED_IN',
    LOGIN_FAILED: 'LOGIN_FAILED',
}